import NavBar from "@/components/Layout/NavBar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Koushik Roy",
  description: "Generated by create next app",
};

export default function BaseLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <NavBar />
      {children}
    </>
  );
}
